# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancestaff',
            options={'verbose_name': 'Maintenance Staff', 'verbose_name_plural': 'Maintenance Staff Members'},
        ),
        migrations.AlterModelOptions(
            name='officestaff',
            options={'verbose_name': 'Office Staff', 'verbose_name_plural': 'Office Staff Members'},
        ),
    ]
