# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180228_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officestaff',
            options={},
        ),
    ]
